let biggestnumber = Number.MAX_VALUE
console.log(biggestnumber)
let smallestnumber = Number.MIN_VALUE
console.log(smallestnumber)
let number1 = 12.45 //floating number 
let number2 = 567 //integer
let number3 = -40 //negative number
console.log(number1)
console.log(number2)
console.log(number3)
/*
Strings - store a sequence of characters
There are three ways to declare a string in JavaScript:
1. Using double quotes: "Hello, World!"
2. Using single quotes: 'Hello, World!'
3. Using backticks (template: `Hello, World!`) used in multiple line strings
*/
let string1 = "Double quotes I am Harmon"
let string2 = 'Single quotes I am Harmon'
let string3 = `
Backticks I am Harmon
I can \n write multiple lines in this string
\t \tI am happy to learn JavaScript
`
let string4 = 'I don\'t eat spaghetti' //single quote escape
console.log(string1)
console.log(string2)
console.log(string3)
console.log(string4)

/* Booleans represent true or false values*/
let isHarmonBrave = true
let isHarmonSlow = false
console.log(isHarmonBrave)
console.log(isHarmonSlow)

//Null represents the luck of a value.
let emptyValue = null
console.log(emptyValue)

//Undefined represents a variable that has been declared but not assigned a value.
let undefinedVal1;
console.log(undefinedVal1)
/*
Don't assign a variable to undefined.
If you want to indicate an undefined variable use null.
*/
